-- RackStage MVP schema.
-- Apply with `supabase db push` or the Supabase SQL editor.
-- Secret-key operations (YouCam, private uploads, reservation RPC) stay in
-- trusted server routes. Anonymous clients receive only published storefront
-- rows through the RLS policies below.

create extension if not exists pgcrypto;

do $$ begin
  create type public.item_status as enum ('draft', 'processing', 'available', 'reserved', 'sold', 'archived');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.processing_operation as enum ('background_removal', 'try_on');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.processing_status as enum ('pending', 'running', 'succeeded', 'failed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.try_on_status as enum ('pending', 'uploading', 'processing', 'succeeded', 'failed', 'expired');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.reservation_status as enum ('active', 'cancelled', 'expired', 'completed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.item_image_kind as enum ('original', 'catalog');
exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Preserve users that existed before this migration was applied.
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  slug text not null check (
    slug = lower(slug)
    and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    and char_length(slug) between 3 and 64
  ),
  logo_path text,
  brand_color text check (brand_color is null or brand_color ~ '^#[0-9a-fA-F]{6}$'),
  pickup_instructions text check (pickup_instructions is null or char_length(pickup_instructions) <= 1000),
  is_public boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (slug)
);

create table if not exists public.items (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  category text check (category is null or category in (
    'shirt', 'blouse', 'top', 'sweater', 'hoodie', 'cardigan',
    'coat', 'jacket', 'dress', 'jumpsuit', 'pants', 'trousers', 'skirt'
  )),
  youcam_category text check (youcam_category is null or youcam_category in ('upper_body', 'full_body', 'lower_body')),
  size text check (size is null or char_length(trim(size)) between 1 and 40),
  brand text check (brand is null or char_length(trim(brand)) between 1 and 100),
  condition text check (condition is null or char_length(trim(condition)) between 1 and 80),
  price numeric(12,2) check (price is null or (price > 0 and price <= 1000000)),
  currency char(3) default 'USD' check (currency is null or currency ~ '^[A-Z]{3}$'),
  notes text check (notes is null or char_length(notes) <= 2000),
  status public.item_status not null default 'draft',
  -- Generated by the trusted create-draft route. Null is allowed for older
  -- clients, while the unique constraint makes retries idempotent when a
  -- request token is supplied.
  client_request_token uuid unique,
  reserved_until timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  -- Draft/processing records may be incomplete while YouCam runs. A seller
  -- can publish only after all required fields are present; catalog image
  -- readiness is checked by the trusted publish route.
  check (
    status in ('draft', 'processing', 'archived')
    or (
      status in ('available', 'reserved', 'sold')
      and category is not null
      and youcam_category is not null
      and size is not null
      and brand is not null
      and condition is not null
      and price is not null
      and currency is not null
      and published_at is not null
    )
  )
);

create table if not exists public.item_images (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items(id) on delete cascade,
  kind public.item_image_kind not null,
  storage_path text not null check (
    char_length(storage_path) between 1 and 1000
    and storage_path not like '%..%'
  ),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png')),
  width integer not null check (width > 0 and width <= 4096),
  height integer not null check (height > 0 and height <= 4096),
  bytes bigint not null check (bytes > 0 and bytes <= 10485760),
  is_public boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  unique (item_id, kind),
  check (is_public = (kind = 'catalog'))
);

create table if not exists public.try_on_sessions (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  source_storage_path text check (source_storage_path is null or (char_length(source_storage_path) between 1 and 1000 and source_storage_path not like '%..%')),
  result_storage_path text check (result_storage_path is null or (char_length(result_storage_path) between 1 and 1000 and result_storage_path not like '%..%')),
  youcam_task_id text,
  status public.try_on_status not null default 'pending',
  error_code text,
  error_message text check (error_message is null or char_length(error_message) <= 1000),
  expires_at timestamptz not null default (timezone('utc', now()) + interval '30 minutes'),
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz
);

create table if not exists public.processing_jobs (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  item_id uuid references public.items(id) on delete cascade,
  try_on_session_id uuid references public.try_on_sessions(id) on delete cascade,
  operation public.processing_operation not null,
  youcam_task_id text,
  status public.processing_status not null default 'pending',
  attempt_count integer not null default 0 check (attempt_count >= 0),
  error_code text,
  error_message text check (error_message is null or char_length(error_message) <= 1000),
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  check (
    (operation = 'background_removal' and item_id is not null and try_on_session_id is null)
    or (operation = 'try_on' and try_on_session_id is not null)
  )
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  request_token uuid not null default gen_random_uuid(),
  buyer_name text not null check (char_length(trim(buyer_name)) between 1 and 120),
  buyer_contact text not null check (char_length(trim(buyer_contact)) between 1 and 200),
  notes text check (notes is null or char_length(notes) <= 500),
  status public.reservation_status not null default 'active',
  reserved_until timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (request_token)
);

create index if not exists stores_owner_idx on public.stores(owner_id);
create index if not exists items_store_status_idx on public.items(store_id, status);
create index if not exists item_images_item_kind_idx on public.item_images(item_id, kind);
create index if not exists processing_jobs_pending_idx on public.processing_jobs(status, created_at)
  where status in ('pending', 'running');
create index if not exists try_on_sessions_expiration_idx on public.try_on_sessions(status, expires_at);
create unique index if not exists try_on_sessions_item_source_unique
  on public.try_on_sessions(item_id, source_storage_path)
  where source_storage_path is not null;
create index if not exists reservations_item_status_idx on public.reservations(item_id, status);
create index if not exists reservations_expiration_idx on public.reservations(status, reserved_until);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists stores_set_updated_at on public.stores;
create trigger stores_set_updated_at before update on public.stores
for each row execute function public.set_updated_at();
drop trigger if exists items_set_updated_at on public.items;
create trigger items_set_updated_at before update on public.items
for each row execute function public.set_updated_at();
drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at before update on public.reservations
for each row execute function public.set_updated_at();

-- New email/magic-link users receive a profile row. The function is
-- intentionally security-definer because auth.users is not client-readable.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name'))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_store_owner(p_store_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.stores
    where id = p_store_id and owner_id = auth.uid()
  );
$$;

create or replace function public.is_item_owner(p_item_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.items i
    join public.stores s on s.id = i.store_id
    where i.id = p_item_id and s.owner_id = auth.uid()
  );
$$;

create or replace function public.storage_path_is_owned(p_path text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  store_id uuid;
begin
  begin
    store_id := split_part(p_path, '/', 1)::uuid;
  exception when invalid_text_representation then
    return false;
  end;
  return public.is_store_owner(store_id);
end;
$$;

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.items enable row level security;
alter table public.item_images enable row level security;
alter table public.processing_jobs enable row level security;
alter table public.try_on_sessions enable row level security;
alter table public.reservations enable row level security;

drop policy if exists profiles_owner_select on public.profiles;
create policy profiles_owner_select on public.profiles for select to authenticated
  using (id = auth.uid());
drop policy if exists profiles_owner_update on public.profiles;
create policy profiles_owner_update on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists stores_owner_all on public.stores;
create policy stores_owner_all on public.stores for all to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists stores_public_read on public.stores;
create policy stores_public_read on public.stores for select to anon, authenticated
  using (is_public = true);

drop policy if exists items_owner_all on public.items;
create policy items_owner_all on public.items for all to authenticated
  using (public.is_store_owner(store_id)) with check (public.is_store_owner(store_id));
drop policy if exists items_public_read on public.items;
create policy items_public_read on public.items for select to anon, authenticated
  using (
    status in ('available', 'reserved', 'sold')
    and exists (select 1 from public.stores s where s.id = store_id and s.is_public = true)
  );

drop policy if exists item_images_owner_all on public.item_images;
create policy item_images_owner_all on public.item_images for all to authenticated
  using (public.is_item_owner(item_id)) with check (public.is_item_owner(item_id));
drop policy if exists item_images_public_catalog_read on public.item_images;
create policy item_images_public_catalog_read on public.item_images for select to anon, authenticated
  using (
    kind = 'catalog' and is_public = true
    and exists (
      select 1 from public.items i
      join public.stores s on s.id = i.store_id
      where i.id = item_id
        and i.status in ('available', 'reserved', 'sold')
        and s.is_public = true
    )
  );

drop policy if exists processing_jobs_owner_select on public.processing_jobs;
create policy processing_jobs_owner_select on public.processing_jobs for select to authenticated
  using (public.is_store_owner(store_id));

drop policy if exists try_on_sessions_owner_select on public.try_on_sessions;
create policy try_on_sessions_owner_select on public.try_on_sessions for select to authenticated
  using (public.is_store_owner(store_id));

drop policy if exists reservations_owner_select on public.reservations;
create policy reservations_owner_select on public.reservations for select to authenticated
  using (public.is_store_owner(store_id));

-- Do not expose direct anonymous writes to any sensitive table. The server
-- route uses service_role and calls the atomic function below.
revoke insert, update, delete on public.profiles, public.stores, public.items,
  public.item_images, public.processing_jobs, public.try_on_sessions,
  public.reservations from anon;

-- Private storage buckets: public storefront URLs are short-lived signed URLs
-- generated by trusted routes after the item RLS check.
insert into storage.buckets (id, name, public)
values ('catalog', 'catalog', false), ('private-buyer', 'private-buyer', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists catalog_owner_manage on storage.objects;
create policy catalog_owner_manage on storage.objects for all to authenticated
  using (bucket_id = 'catalog' and public.storage_path_is_owned(name))
  with check (bucket_id = 'catalog' and public.storage_path_is_owned(name));

drop policy if exists private_buyer_no_direct_access on storage.objects;
create policy private_buyer_no_direct_access on storage.objects for all to anon, authenticated
  using (false) with check (false);

-- Public-safe views are useful to clients that do not need owner IDs or draft
-- fields. The base-table policies above remain the source of truth.
create or replace view public.public_storefronts as
select id, name, slug, logo_path, brand_color, pickup_instructions
from public.stores
where is_public = true;

create or replace view public.public_storefront_items as
select i.id, i.store_id, i.category, i.youcam_category, i.size, i.brand,
  i.condition, i.price, i.currency, i.notes, i.status, i.reserved_until,
  i.published_at
from public.items i
join public.stores s on s.id = i.store_id
where s.is_public = true and i.status in ('available', 'reserved', 'sold');

create or replace view public.public_catalog_images as
select ii.id, ii.item_id, ii.storage_path, ii.mime_type, ii.width, ii.height
from public.item_images ii
join public.items i on i.id = ii.item_id
join public.stores s on s.id = i.store_id
where ii.kind = 'catalog' and ii.is_public = true
  and s.is_public = true and i.status in ('available', 'reserved', 'sold');

grant select on public.public_storefronts, public.public_storefront_items,
  public.public_catalog_images to anon, authenticated;

-- Anonymous storefront reads go through the column-safe views above. This
-- prevents draft-only fields such as client_request_token, owner IDs, and
-- private processing paths from being selected through a base-table wildcard.
revoke select on public.profiles, public.stores, public.items, public.item_images,
  public.processing_jobs, public.try_on_sessions, public.reservations from anon;

-- Expiration is deliberately a simple database function. Call it before
-- storefront reads and reservations (or schedule it with Supabase Cron) so a
-- reservation can never block a one-of-one item after its deadline.
create or replace function public.release_expired_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  released integer := 0;
begin
  update public.reservations
  set status = 'expired', updated_at = timezone('utc', now())
  where status = 'active' and reserved_until <= timezone('utc', now());

  update public.items i
  set status = 'available', reserved_until = null, updated_at = timezone('utc', now())
  where i.status = 'reserved'
    and i.reserved_until is not null
    and i.reserved_until <= timezone('utc', now())
    and not exists (
      select 1 from public.reservations r
      where r.item_id = i.id and r.status = 'active'
        and r.reserved_until > timezone('utc', now())
    );
  get diagnostics released = row_count;
  return released;
end;
$$;

-- Mark expired shopper sessions and return the private paths that a trusted
-- server must delete through the Supabase Storage API. Do not delete directly
-- from storage.objects: SQL metadata deletion can leave the underlying object
-- behind. Once the server has deleted the paths, it should clear them and may
-- remove the expired session row. Keep this function small enough to call
-- opportunistically from a trusted route or schedule with Supabase Cron.
drop function if exists public.cleanup_expired_try_ons();
create function public.cleanup_expired_try_ons()
returns table (
  session_id uuid,
  source_storage_path text,
  result_storage_path text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.try_on_sessions
  set status = 'expired', completed_at = coalesce(completed_at, timezone('utc', now()))
  where expires_at <= timezone('utc', now()) and status <> 'expired';

  -- Rows whose paths are already null were physically cleaned by the server;
  -- remove those old markers after one additional day. Rows with paths remain
  -- so a later cleanup call can return them again if a delete was interrupted.
  delete from public.try_on_sessions
  where status = 'expired'
    and source_storage_path is null
    and result_storage_path is null
    and expires_at <= timezone('utc', now()) - interval '1 day';
  return query
  select s.id, s.source_storage_path, s.result_storage_path
  from public.try_on_sessions s
  where s.status = 'expired'
    and s.expires_at <= timezone('utc', now())
    and (s.source_storage_path is not null or s.result_storage_path is not null)
  order by s.expires_at asc;
end;
$$;

create or replace function public.reserve_item(
  p_item_id uuid,
  p_reserved_until timestamptz,
  p_buyer_name text,
  p_buyer_contact text,
  p_notes text default null,
  p_request_token uuid default gen_random_uuid()
)
returns public.reservations
language plpgsql
security definer
set search_path = public
as $$
declare
  existing public.reservations;
  inserted public.reservations;
  item_store_id uuid;
begin
  perform public.release_expired_reservations();

  if p_reserved_until <= timezone('utc', now())
    or p_reserved_until > timezone('utc', now()) + interval '48 hours' then
    raise exception using errcode = '22023', message = 'invalid_reservation_window';
  end if;
  if char_length(trim(coalesce(p_buyer_name, ''))) = 0
    or char_length(trim(coalesce(p_buyer_contact, ''))) = 0 then
    raise exception using errcode = '22023', message = 'buyer_details_required';
  end if;

  select * into existing from public.reservations where request_token = p_request_token;
  if found then return existing; end if;

  update public.items
  set status = 'reserved', reserved_until = p_reserved_until,
      updated_at = timezone('utc', now())
  where id = p_item_id and status = 'available'
  returning store_id into item_store_id;

  if item_store_id is null then
    -- A concurrent idempotent request may have committed while this request
    -- waited for the item row lock. Return it instead of creating a duplicate.
    select * into existing from public.reservations where request_token = p_request_token;
    if found then return existing; end if;
    raise exception using errcode = 'P0001', message = 'item_unavailable';
  end if;

  insert into public.reservations (
    item_id, store_id, request_token, buyer_name, buyer_contact, notes,
    status, reserved_until
  ) values (
    p_item_id, item_store_id, p_request_token, trim(p_buyer_name),
    trim(p_buyer_contact), nullif(trim(p_notes), ''), 'active', p_reserved_until
  )
  on conflict (request_token) do nothing
  returning * into inserted;

  if inserted.id is null then
    select * into existing from public.reservations where request_token = p_request_token;
    if found then return existing; end if;
    raise exception using errcode = 'P0001', message = 'reservation_failed';
  end if;
  return inserted;
end;
$$;

-- Supabase service_role is the only role allowed to run these server-side
-- operations. No anonymous database write can bypass this boundary.
revoke all on function public.release_expired_reservations() from public, anon, authenticated;
grant execute on function public.release_expired_reservations() to service_role;
revoke all on function public.cleanup_expired_try_ons() from public, anon, authenticated;
grant execute on function public.cleanup_expired_try_ons() to service_role;
revoke all on function public.reserve_item(uuid, timestamptz, text, text, text, uuid) from public, anon, authenticated;
grant execute on function public.reserve_item(uuid, timestamptz, text, text, text, uuid) to service_role;
